#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kerberos
Version  : 1.2.4
Release  : 7
URL      : https://pypi.python.org/packages/source/k/kerberos/kerberos-1.2.4.tar.gz
Source0  : https://pypi.python.org/packages/source/k/kerberos/kerberos-1.2.4.tar.gz
Summary  : Kerberos high-level interface
Group    : Development/Tools
License  : Apache-2.0
Requires: kerberos-python
BuildRequires : krb5-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(com_err)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
PyKerberos Package
==================
This Python package is a high-level wrapper for Kerberos (GSSAPI)
operations.  The goal is to avoid having to build a module that wraps
the entire Kerberos.framework, and instead offer a limited set of
functions that do what is needed for client/server Kerberos
authentication based on <http://www.ietf.org/rfc/rfc4559.txt>.

%package python
Summary: python components for the kerberos package.
Group: Default

%description python
python components for the kerberos package.


%prep
%setup -q -n kerberos-1.2.4

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
