#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kerberos
Version  : 1.1.1
Release  : 4
URL      : https://pypi.python.org/packages/source/k/kerberos/kerberos-1.1.1.tar.gz
Source0  : https://pypi.python.org/packages/source/k/kerberos/kerberos-1.1.1.tar.gz
Summary  : Kerberos high-level interface
Group    : Development/Tools
License  : Apache-2.0
Requires: kerberos-python
BuildRequires : krb5-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(com_err)
BuildRequires : python-dev
BuildRequires : setuptools

%description
=========================================================
PyKerberos Package
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

%package python
Summary: python components for the kerberos package.
Group: Default

%description python
python components for the kerberos package.


%prep
%setup -q -n kerberos-1.1.1

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
